version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongo_db01
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: yusufo
      MONGO_INITDB_ROOT_PASSWORD: yusufo
    networks:
      - app_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express01
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: yusufo
      ME_CONFIG_MONGODB_ADMINPASSWORD: yusufo
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: myuser
      ME_CONFIG_BASICAUTH_PASSWORD: mypassword  
    depends_on:
      - mongodb
    networks:
      - app_network

volumes:
  mongo_data: {}
